name: Update Playwright Snapshots

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          cache: npm
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - run: npm run build && npx playwright test --update-snapshots
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update playwright snapshots"
          file_pattern: "tests/snapshots/*.png"
